### ISSUE TITLE
tcr_dict_distance_matrix

### ISSUE THREAD

**Issue by XUTONG-GONG** [agartland/pwseqdist#9]
Hello,

Thanks for the awesome package! However I do have a question about tcr_dict_distance_matrix on line 59 in matrices.py. How did you come up with the numbers for each amino acid pair? I tried to convert blosum62 matrix to distance matrix using kernel2dist function, but the result was not even close to those numbers in tcr_dict_distance_matrix.
Thanks so much in advance!

**Comment by agartland** [comment]
Hi,
Glad you use and like the package! I'm sorry its a bit confusing how the TCRdist is computed. Firstly, you will see in this code that TCRdist includes weights for the CDR3 vs. CDR1/2: [tcrdist distance functions](https://github.com/kmayerb/tcrdist3/blob/master/tcrdist/rep_funcs.py)

The explanation is in our first paper, [Dash et al.](https://www.nature.com/articles/nature22383). See the Methods section under the section "TCRdist distance measure"

That should explain the distance matrix that you see on [line 59](https://github.com/agartland/pwseqdist/blob/852e159ad12582973bfbf23dd33fef068723742e/pwseqdist/matrices.py#L59C4-L59C4)

Btw, there aren't strong theoretical reasons why this should work any better for TCR analysis compared to a straight BLOSUM matrix  or some other specialized matrix (indeed some of the new research by others in this field is in improving this matrix!) We continue to use this original matrix for continuity and our familiarity with it, but may update the matrix when there is strong evidence of improvement. My point is that you too should feel free to experiment with new matrices and let us know what you find!

Andrew
